docs/jupiterone.md

Fixes #15 - Create Google Cloud integration setup instructions

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/steps/compute/converters.ts
src/steps/compute/index.ts
src/steps/functions/index.ts
src/steps/iam/converters.ts
src/steps/iam/index.ts
src/steps/resource-manager/converters.ts
src/steps/resource-manager/index.ts
src/steps/service-usage/index.ts
src/steps/storage/index.ts
yarn.lock

Upgrade to SDK v3.0.0

---

src/steps/storage/__recordings__/fetchCloudStorageBuckets_582254432/recording.har
src/steps/storage/__snapshots__/converters.test.ts.snap
src/steps/storage/__snapshots__/index.test.ts.snap
src/steps/storage/client.ts
src/steps/storage/converters.test.ts
src/steps/storage/converters.ts
src/steps/storage/index.test.ts
src/steps/storage/index.ts
src/utils/iam.ts
terraform/cloud_storage_buckets.tf

We should also ingest the policy and build a relationship between the policy and the bucket, but this will help us answer:
```
find google_compute_bucket with public=true
```

Add public property to google_storage_bucket

---

CHANGELOG.md
package.json
src/steps/kms/constants.ts
src/steps/kms/index.test.ts
src/steps/resource-manager/__recordings__/fetchResourceManagerProjectWithDisabledApi_3467224869/recording.har
src/steps/resource-manager/__snapshots__/index.test.ts.snap
src/steps/resource-manager/converters.test.ts
src/steps/resource-manager/converters.ts
src/steps/resource-manager/index.test.ts
src/steps/resource-manager/index.ts

38 try fetching project

---

CHANGELOG.md
docs/jupiterone.md
package.json
scripts/__recordings__/setupOrganization_2957442745/recording.har
scripts/organizationSetup.test.ts
scripts/organizationSetup.ts
scripts/organizationSetupCli.ts
src/google-cloud/client.ts
src/steps/resource-manager/index.ts
test/recording.ts
yarn.lock

every Google Cloud project in an organization

Create script that allows JupiterOne integration instance creation for

---

docs/jupiterone.md

New role required for GCP integration to ingest without error

Add aim.roleViewer requirement to docs

---

docs/jupiterone.md
package.json
scripts/__recordings__/setupOrganizationWithIntegrationNamePattern_678465348/recording.har
scripts/organizationSetup.test.ts
scripts/organizationSetup.ts
scripts/organizationSetupCli.ts
yarn.lock

Usage:
```
yarn jupiterone-organization-setup --integration-instance-name-pattern "gcp-{{projectId}}" ...
```

Allow prefixing project names from org script

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/steps/compute/index.ts
src/utils/events.ts

- Update CHANGELOG.md
- Update setup doc supported services

Publish integration job log event when compute.projects.get missing

---

.gitignore
terraform/.terraform.lock.hcl
terraform/cloud_functions.tf
terraform/cloud_storage_buckets.tf
terraform/main.tf
terraform/monitoring.tf
terraform/vars.tf

Add required versions to Terraform

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/steps/compute/__snapshots__/converters.test.ts.snap
src/steps/compute/__snapshots__/index.test.ts.snap
src/steps/compute/constants.ts
src/steps/compute/converters.test.ts
src/steps/compute/converters.ts
src/steps/compute/index.ts

```
find google_container_cluster
THAT HAS google_compute_instance_group
THAT HAS google_compute_instance_group_node_port
with name="abc" and port=123
return
google_compute_instance_group.*
```

Add support for google_compute_instance_group_node_port

---

CHANGELOG.md
docs/jupiterone.md
package.json

Waiting for #88 to merge before actually versioning.

Version 0.18.0

---

terraform/compute_vms.tf
terraform/databases.tf
terraform/gke.tf
terraform/output.tf
terraform/vars.tf

Deprovision various resources

---

CHANGELOG.md
docs/jupiterone.md
src/steps/functions/constants.ts
src/steps/functions/index.ts
terraform/cloud_functions.tf

```
find google_cloud_function THAT USES
THAT USES google_iam_service_account
return
google_cloud_function.name,
google_cloud_function.webLink,
google_iam_service_account.name,
google_iam_service_account.email,
google_iam_service_account.webLink
```

Create relationship between cloud function and service account

---

src/steps/storage/index.ts

Attempts to fix the _Cloud storage bucket that is configured "requestor pays" cannot be read_ #107 issue.
When the bucket has requester pays settings turned ON, the problem arises when we attempt to fetch its policy `client.getPolicy(bucketId)`. The current version of this fix skips over these buckets and doesn't insert them in the graph. If we want to, we could still insert them in the graph but we just wouldn't be able to tell if they're public or not (that's derived from the policy). In that case, we could either default to some value or perhaps set their isPublic values to undefined in this case.
Before:
After:
Pinging: @aiwilliams @austinkelleher

Fix #107 - Add custom error for bucket requester pays

---

src/steps/monitoring/index.ts
src/utils/events.ts

Attempt to fix the #116 @austinkelleher

Add alertPolicies step error handling

---

CHANGELOG.md
package.json
src/steps/storage/converters.ts
src/steps/storage/index.ts
src/utils/events.ts

Fixes #126 - Ingest bucket even if policy cannot be fetched

---

src/steps/compute/index.ts

#152's issue was that we didn't log/inform the customer in case they didn't have `compute.images.get` permission set.
#153's issue was that the code didn't handle blank disks (disks that don't have an image assigned)

Handle blank disks and compute.images.get permission - Fix #152, #153

---

CHANGELOG.md
package.json
src/index.test.ts
src/index.ts
yarn.lock

Using: https://github.com/JupiterOne/sdk/pull/471

Fixes #175 - Add projectId to every entity

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/steps/big-query/__snapshots__/converters.test.ts.snap
src/steps/big-query/__snapshots__/index.test.ts.snap
src/steps/big-query/constants.ts
src/steps/big-query/index.test.ts
yarn.lock

FYI @eXtremeX. We decided to introduce a new class called `DataCollection`. We had considered `DataTable`, but that makes assertions about the structure of the data (in table form).
> What tables do my databases use?
```
FIND Database
THAT HAS DataCollection
```

Update `google_bigquery_table` `_class` to `DataCollection`

---

scripts/organizationSetup.test.ts
scripts/organizationSetup.ts
src/google-cloud/client.test.ts
src/index.test.ts
src/index.ts
src/steps/api-gateway/client.ts
src/steps/api-gateway/index.ts
src/steps/compute/index.test.ts
src/steps/compute/index.ts
src/steps/iam/index.test.ts
src/steps/iam/index.ts
src/steps/kms/client.ts
src/steps/kms/index.test.ts
src/steps/privateca/client.ts
src/steps/privateca/index.ts
src/steps/resource-manager/index.test.ts
src/steps/resource-manager/index.ts
src/steps/service-usage/client.ts
src/steps/sql-admin/index.test.ts
src/types.ts
src/utils/entity.ts
src/utils/parseServiceAccountKeyFile.test.ts
test/config.ts
test/mocks.ts
test/recording.ts

We haven't run `yarn lint/format` in some time, this PR just wants to sync those changes with the master.

Apply lint & format

---

CHANGELOG.md
src/getStepStartStates.ts
src/google-cloud/types.ts

Fixes #186 - Accept `storage-api` and `storage-component` services to enable buckets step

---

docs/jupiterone.md
package.json
src/getStepStartStates.ts
src/index.test.ts
src/steps/compute/__snapshots__/converters.test.ts.snap
src/steps/compute/__snapshots__/index.test.ts.snap
src/steps/compute/client.ts
src/steps/compute/constants.ts
src/steps/compute/converters.ts
src/steps/compute/index.ts

Will go back and add some tests. I tested this in dev.

Ingest google_compute_snapshots and build various relationships between compute resources

---

src/steps/compute/index.ts

This PR adds changes requested here #244 - cc @austinkelleher

Small adjustments to VPC peering

---

CHANGELOG.md
package.json
src/getStepStartStates.ts
src/index.test.ts
src/steps/enablement.test.ts
src/steps/enablement.ts
src/steps/functions/__snapshots__/converters.test.ts.snap
src/steps/functions/constants.ts
src/steps/functions/converters.ts
src/steps/functions/index.ts

Always execute steps in org child projects even if child project has service disabled

---

src/steps/compute/index.ts

Handle case where the public image is deprecated

---

CHANGELOG.md
package.json
src/utils/url.ts
yarn.lock

- Encode path part of `webLink` entity property

- Upgraded integration SDK packages to v6.13.0

---

src/steps/cloud-asset/index.ts
src/steps/sql-admin/__snapshots__/converters.test.ts.snap
src/steps/sql-admin/__snapshots__/index.test.ts.snap
src/steps/sql-admin/converters.ts
src/steps/sql-admin/index.test.ts
src/utils/iamBindings/__snapshots__/getTypeAndKeyFromResourceIdentifier.test.ts.snap
src/utils/iamBindings/resourceKindToTypeMap.ts
src/utils/iamBindings/typeToKeyGeneratorMap.ts

Needed to change the `_key` property from SQL resources to something that can be found from the resource identifiers. Also changed the relationship mappings to only check the `_key` property which should be fine because the key is a url which is globally unique.

INT-1302 binding to sql relationships

---

src/steps/compute/__snapshots__/index.test.ts.snap
src/steps/compute/index.ts

This handles the case where custom image have been deleted (we talked about this @austinkelleher)

Handle deleted custom images

---

CHANGELOG.md
src/steps/cloud-asset/converters.ts
src/steps/iam/converters.ts

Truncate large arrays when storing them in rawData for roles and bindings.

INT-1922 - request too large

---

.github/workflows/build.yml

It looks like these secrets were updated to the organization scope.

Update managed question secrets

---

src/steps/cloud-asset/index.ts

- Step "IAM Bindings" failed to complete due to error. (errorCode="PROVIDER_API_ERROR", errorId="4c9644b8-324e-4ea9-bdf4-58fe5105500d", reason="Provider API failed at https://cloudasset.googleapis.com/v1/projects/null:searchAllIamPolicies?pageSize=500: 400 Bad Request"

Only fetch project IAM bindings if there is a project

---

CHANGELOG.md
jupiterone/questions/questions.yaml
src/steps/app-engine/__snapshots__/index.test.ts.snap
src/steps/compute/__snapshots__/index.test.ts.snap
src/steps/compute/index.test.ts
src/steps/dataproc/__snapshots__/index.test.ts.snap
src/steps/dataproc/index.test.ts
src/steps/logging/__snapshots__/index.test.ts.snap
src/steps/logging/index.test.ts
src/steps/logging/index.ts
src/steps/privateca/__snapshots__/index.test.ts.snap
src/steps/storage/__snapshots__/converters.test.ts.snap
src/steps/storage/__snapshots__/index.test.ts.snap
src/steps/storage/converters.test.ts
src/steps/storage/converters.ts
src/steps/storage/index.test.ts

INT-2233 - Add `versioningEnabled` to `google_storage_bucket`

---

CHANGELOG.md
src/google-cloud/client.test.ts
src/steps/cloud-asset/__recordings__/iterateIamPoliciesForProjectAndResources_3454369950/recording.har
src/steps/cloud-asset/__snapshots__/client.test.ts.snap
src/steps/cloud-asset/client.test.ts
src/steps/cloud-asset/client.ts
src/steps/cloud-asset/index.ts

This is what is specified in the integration config page, so we should be doing the same in the code.

INTS-121 - Properly default projectId to serviceAccount projectId when not specified

---

CHANGELOG.md
src/steps/app-engine/index.ts

The problem is described in details in [Jira task](https://jupiterone.atlassian.net/browse/INT-3172).

INT-3172 - Add better handling for app engine services

---

jupiterone/questions/questions.yaml

add GCP service accounts permissions managed question

add GCP service accounts permissions question

---

CHANGELOG.md
package.json

Need to get some of these updated questions out. Lemme know if you'd like more details in the changelog.

Publish latest questions

---

docs/jupiterone/multi-project-console.md
docs/jupiterone/multi-project-gcloud.md
docs/jupiterone/single-project-console.md
docs/jupiterone/single-project-gcloud.md

Same as #493 but for the new docs branch.

Update BigQuery docs part

---

.github/workflows/build.yml
.github/workflows/questions.yml
package.json
yarn.lock

This PR adds the new graph:dependencies command and may update dependencies if out of date

Add graph:dependencies command, update deps

---

docs/jupiterone.md
src/getStepStartStates.ts
src/index.test.ts
src/steps/cloud-build/client.ts
src/steps/cloud-build/constants.ts
src/steps/cloud-build/converters.ts
src/steps/cloud-build/index.ts
src/steps/cloud-build/steps/__recordings__/fetch-cloud-build-ghe-configs_3514519803/recording.har
src/steps/cloud-build/steps/fetch-cloud-build-ghe-configs.test.ts
src/steps/cloud-build/steps/fetch-cloud-build-ghe-configs.ts
test/recording.ts

Adds support for https://cloud.google.com/build/docs/api/reference/rest/v1/projects.githubEnterpriseConfigs

INT-5236: step-fetch-cloud-build-ghe-configs

---

docs/jupiterone.md
src/getStepStartStates.ts
src/index.test.ts
src/steps/cloud-build/client.ts
src/steps/cloud-build/constants.ts
src/steps/cloud-build/converters.ts
src/steps/cloud-build/index.ts
src/steps/cloud-build/steps/__recordings__/fetch-cloud-build-bb-configs_3549344971/recording.har
src/steps/cloud-build/steps/fetch-cloud-build-bb-configs.test.ts
src/steps/cloud-build/steps/fetch-cloud-build-bb-configs.ts
test/recording.ts

Add support for https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.bitbucketServerConfigs/list

INT-5237 step: fetch-cloud-build-bb-configs

---

docs/jupiterone.md
src/getStepStartStates.ts
src/index.test.ts
src/steps/cloud-build/client.ts
src/steps/cloud-build/constants.ts
src/steps/cloud-build/converters.ts
src/steps/cloud-build/index.ts
src/steps/cloud-build/steps/__recordings__/fetch-cloud-build-bb-repos_1051036273/recording.har
src/steps/cloud-build/steps/fetch-cloud-build-bb-configs.ts
src/steps/cloud-build/steps/fetch-cloud-build-bb-repos.test.ts
src/steps/cloud-build/steps/fetch-cloud-build-bb-repos.ts
src/steps/cloud-build/steps/fetch-cloud-build-ghe-configs.ts
src/steps/cloud-build/steps/fetch-cloud-build-triggers.ts
src/steps/cloud-build/steps/fetch-cloud-build-worker-pools.ts
src/steps/cloud-build/steps/fetch-cloud-builds.ts

Add support for https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.bitbucketServerConfigs.repos/list

INT-5238/INT-5292 step: fetch-cloud-build-bb-repos / relationship: google_cloud_bitbucket_server_config_has_repo

---

docs/jupiterone.md
src/getStepStartStates.ts
src/index.test.ts
src/steps/cloud-build/constants.ts
src/steps/cloud-build/converters.ts
src/steps/cloud-build/index.ts
src/steps/cloud-build/steps/__recordings__/build-cloud-build-trigger-triggers-build-relationships_629914260/recording.har
src/steps/cloud-build/steps/build-cloud-build-trigger-triggers-build-relationships.test.ts
src/steps/cloud-build/steps/build-cloud-build-trigger-triggers-build-relationships.ts

quick note on this: `google_cloud_build_trigger.build` in the doc actually refers to a template for the trigger, I’ve instead mapped build with the trigger of said build using `buildTriggerId` field on build.
I still feel like `triggers` is not the right term for this relationship as the build gets `created`

INT-5293 step: build-cloud-build-trigger-triggers-build-relationships

---

docs/jupiterone.md
src/getStepStartStates.ts
src/index.test.ts
src/steps/cloud-build/constants.ts
src/steps/cloud-build/index.ts
src/steps/cloud-build/steps/__recordings__/build-cloud-build-uses-storage-bucket-relationships_4186298260/recording.har
src/steps/cloud-build/steps/build-cloud-build-uses-storage-bucket-relationships.test.ts
src/steps/cloud-build/steps/build-cloud-build-uses-storage-bucket-relationships.ts
test/recording.ts

Note: This was pushed with --no-verify as I had issues running the fetch cloud storage.
- For testing purposes I had to add `if (bucket.name?.includes('us-central1')) return;` to `storage/index.ts`; once that was added I was able to get the following picture.

INT-5288 step: build-cloud-build-storage-bucket-relationships

---

docs/jupiterone.md
src/getStepStartStates.ts
src/index.test.ts
src/steps/cloud-build/constants.ts
src/steps/cloud-build/index.ts
src/steps/cloud-build/steps/__recordings__/build-cloud-build-trigger-uses-github-repo_668859737/recording.har
src/steps/cloud-build/steps/build-cloud-build-trigger-uses-github-repo-relationships.test.ts
src/steps/cloud-build/steps/build-cloud-build-trigger-uses-github-repo-relationships.ts

This creates mapped relationships betwen gh repos and build triggers

Add step: build-cloud-build-trigger-uses-github-repo-relationships

---

docs/spec/src/steps/services/build/index.ts

Missed a few comments from #507

Fix build spec properties

---

docs/jupiterone.md
docs/spec/src/steps/services/functions/index.ts
src/getStepStartStates.ts
src/index.test.ts
src/steps/functions/__recordings__/build-cloud-function-source-repo-relationships_912814797/recording.har
src/steps/functions/__snapshots__/converters.test.ts.snap
src/steps/functions/constants.ts
src/steps/functions/converters.ts
src/steps/functions/index.test.ts
src/steps/functions/index.ts
test/mocks.ts

Adds Google Cloud Functions Source Repository Relation.

feat(INT-5918): add cloud function source repo relationship

---

.github/workflows/build.yml
.github/workflows/questions.yml

Fixes GH action issues. Please notice this will take effect after merged.

fix(INT-6619): fix GH action issue

---

docs/jupiterone.md
src/getStepStartStates.ts
src/google-cloud/types.ts

Log to integration job useful information for the user when an API service is disabled resulting on a specific set of steps being disabled. Example output:

feat(INT-5712): log disabled steps by API Service

---

package.json
src/steps/cloud-asset/index.test.ts
src/steps/compute/__snapshots__/index.test.ts.snap
yarn.lock

- Reduced log level of graph object uploads from info to debug

Bump SDK Version

---

src/steps/compute/index.ts

Avoid making extra api calls if inventory api is disabled. Iterating thought a large amount of compute instances and trying to fetch instance inventory with the API disabled generates alerts in the dashboard.

INT-8705: avoid extra inventory calls if api is disabled

---

jupiterone/questions/questions.yaml

adding exisiting mappings for versions 1.1-1.3-2.0

Add mappings 1.1-3.4

---

docs/jupiterone.md

No functional changes, needed to release the changes in this PR: https://github.com/JupiterOne/graph-google-cloud/pull/633

Bump package version

---

docs/jupiterone.md
jupiterone/questions/questions.yaml

The diff is large because the file was reformatted but the only change is one duplicate question removed based on customer feedback
https://jupiterone.atlassian.net/browse/APP-14216?focusedCommentId=59438

APP-14216 - Remove duplicate question

---

jupiterone/questions/questions.yaml

Just getting questions released that were merged in a recent PR: https://github.com/JupiterOne/graph-google-cloud/pull/690

Release questions
