- CHANGELOG.md
- package.json
- src/steps/resource-manager/index.test.ts
- src/steps/resource-manager/index.ts
The previous code always created a `User` entity in this step, not taking into account that the previous `PolicyMemberBinding`s could target the same user. Fixed by always checking if a user exists before creating the relationship.
Once I get an approval I'll bump the version (minor to `3.1.0`, instead of patch to `3.0.1`, because there are other unreleased changes noted in the `CHANGELOG`).
> Fix DUPLICATE_KEY_ERR in fetchResourceManagerIamPolicy

- CHANGELOG.md
- package.json
- src/steps/compute/__snapshots__/index.test.ts.snap
- src/steps/compute/converters.ts
Relationship properties cannot be arrays or objects.
Opened https://github.com/JupiterOne/sdk/issues/344 to track implementation of a new matcher.
I'll version bump if you guys approve.
> Fix relationship array property

- docs/jupiterone.md
- src/getStepStartStates.ts
- src/google-cloud/types.ts
- src/index.test.ts
- src/index.ts
- src/steps/kms/__recordings__/fetchKmsCryptoKeys_2580116173/recording.har
- src/steps/kms/__recordings__/fetchKmsKeyRings_3543545506/recording.har
- src/steps/kms/__snapshots__/converters.test.ts.snap
- src/steps/kms/__snapshots__/index.test.ts.snap
- src/steps/kms/client.ts
- src/steps/kms/constants.ts
- src/steps/kms/converters.test.ts
- src/steps/kms/converters.ts
- src/steps/kms/index.test.ts
- src/steps/kms/index.ts
- src/utils/time.ts
NOTE: This branches off of `initial-networking`
> Support for ingesting KSM crypto key rings and crypto keys

- CHANGELOG.md
- docs/development.md
- package.json
- src/steps/resource-manager/index.ts
Previously, if `err.message` existed and the error was a 403, we would _only_ display `Caller does not have permission` in the job log. Now, we will display the full remediation message:
`Could not fetch project from Cloud Resource Manager API. Ensure the API is enabled (see 'https://github.com/JupiterOne/graph-google-cloud/blob/master/docs/development.md#enabling-google-cloud-services) {code:403,message:'Caller does not have permission'}`
Related to #38
> Improve experience of '403: Caller does not have permission' error

- terraform/iam.tf
- terraform/vars.tf
This PR does few things:
- It recognizes and ingests the `integration_runner_service_account_client_email` variable coming from the Terraform Cloud.
- It creates a new custom role that adds all the necessary permissions for the integration (that Security Reviewer role otherwise doesn't include by default). This allows us to keep track of what changes are necessary.
- It binds that custom role to the `integration_runner_service_account_client_email` which represents the service account used for running the integration.
PS. This was discussed with @austinkelleher yesterday.
CC @aiwilliams @ndowmon @mknoedel
> Add custom role binding for the sa integration runner

- terraform/vars.tf
@austinkelleher Deletes the Redis instance using Terraform as we no longer need it to be present in Google Cloud.
> Delete redis instance using Terraform

- terraform/vars.tf
@austinkelleher Deletes the Spanner instance using Terraform as we no longer need it to be present in Google Cloud.
> Delete spanner instance using Terraform

- src/steps/storage/index.ts
- src/utils/events.ts
Uses the `logger.publishEvent` to send an informative message about unprocessed buckets.
@austinkelleher, @aiwilliams
> Improve buckets requester pays logging (related to #107)

- src/google-cloud/client.ts
Attempts to fix the _Monitoring Alert Policies step fails when a project is not assigned to a workspace_ #108 issue.
This is very _experimental_ because I wasn't able to modify my gcloud environment to run into this example where some project is not a workspace. Tried creating multiple projects and then merging their workspaces to get into a state where some project isn't a workspace (but is instead part of another workspace) and then to run integration using that project's credentials, but just didn't work for me for some reasons.
This change, unless I'm mistaken, should replace the UNKNOWN part and the error *should* look something similar to this:
`17:00:45.042Z ERROR Local: Step "Monitoring Alert Policies" failed to complete due to error. (errorCode="PROVIDER_API_ERROR", …
> Fix #108 - Provide message instead of UNKNOWN when project is not a workspace

- CHANGELOG.md
- src/steps/app-engine/__snapshots__/index.test.ts.snap
- src/steps/iam/__snapshots__/converters.test.ts.snap
- src/steps/iam/__snapshots__/index.test.ts.snap
- src/steps/iam/converters.ts
- src/steps/iam/index.test.ts
- src/steps/resource-manager/__snapshots__/index.test.ts.snap
- src/utils/iam.test.ts
- src/utils/iam.ts
This is a bit of a clever method in order to answer the following questions without complex J1QL filtering:
> Which Google Cloud roles are read-only?
```
find google_iam_role with readonly=true
```
> Which Google Cloud roles have write access?
```
find google_iam_role with readonly=false
```
> Add readonly property to google_iam_role

- CHANGELOG.md
- package.json
- src/steps/app-engine/index.ts
This is kind of a hack. I added some additional logging and will clean it up when I know more. This should never cause the step to fail though.
> Fixes #171 - Suppress error when App Engine applications cannot be fetched

- CHANGELOG.md
- package.json
- src/getStepStartStates.ts
- src/index.test.ts
- src/index.ts
- src/types.ts
`configureOrganizationProjects` is the actual config property name.
FYI @eXtremeX
> Rename configureOrganizationAccounts integration config property to configureOrganizationProjects

- docs/jupiterone.md
`roles/bigquery.dataViewer` is a bit over provisioned. J1 currently only needs access to these APIs:
```
bigquery.tables.list
bigquery.tables.getIamPolicy
bigquery.datasets.list
bigquery.datasets.get
bigquery.models.list
bigquery.models.get
```
> Update BigQuery documentation to use more appropriate role

- src/steps/compute/__snapshots__/converters.test.ts.snap
- src/steps/compute/__snapshots__/index.test.ts.snap
- src/steps/compute/converters.test.ts
- src/steps/compute/converters.ts
- src/steps/compute/index.ts
- src/utils/firewall.test.ts
- src/utils/firewall.ts
INT-1198 - Required using indicates in the key because rules can specify the same protocol + IP + port and the key wasn't unique enough before.
> Upgrade firewall relationships keys (duplicate key issue)

- src/steps/resource-manager/index.ts
INT-1200
The issue was the following: If the Cloud Resource Manager service was disabled, we wouldn't have gotten the project in the code (near this fix) and the `cacheProjectNameToId` wouldn't be able to work. We've moved it to inside the try-catch block so that it never executes if the service is disabled.
> Handle cache name case where project is not available

- src/steps/app-engine/index.ts
INT-1199
We want to suppress the error if the AppEngine project hasn't yet been created/doesn't exist.
> Handle case where AppEngine project is not found

- CHANGELOG.md
This is a very simple PR: we haven't been updating changelogs in our previous PRs that got merged, this PR updates the changelog with all of those changes.
PRs changes contained within this PR are the following:
- INT-1208 - Ingest Dataproc clusters
- INT-1552 - Add Dataproc Cluster Image relationships
- INT-1237 & INT-1239 - Add Cloud Billing resources and Billing Budget
- INT-1553 - Add Dataproc Cluster Storage relationships
- INT-1236 - Add BigTable resources
- INT-1547 - Add a separate step to build relationship from BigQuery dataset to KMS
Pinging @aiwilliams @austinkelleher @ndowmon @mknoedel
> INT-1697 - Add past changelogs

- .gitignore
- CHANGELOG.md
- docs/development.md
- src/steps/compute/__snapshots__/index.test.ts.snap
- src/utils/firewall.test.ts
- src/utils/firewall.ts
Fixes missing internet allows firewall relationship from appearing in the graph on entities with `ingress: true`  + and an IP range of `0.0.0.0/0` by: setting `targetFilterKeys` to use both `_key` *and* `_type` (see existing `isInternet` usage for more info).
I'm trying to come up with a better explanation of why this worked so if anyone would like to enlighten me, please feel free to discuss more.
**Steps to Reproduce**
1. Create a new firewall entity that has not been used before (`gcloud compute firewall-rules create some-new-name --allow=tcp:XXXX --source-ranges="0.0.0.0/0" --description="Allow incoming traffic" --direction=INGRESS`)
2. Run your custom integration from the  `main` branch (`yarn run -i <id> -d`)
3. Observe the firewall has no internet allows connection. You may want to …
> INTS-23: Fix missing Internet --ALLOWS--> Firewall relationship

- CHANGELOG.md
- package.json
- src/steps/cloud-asset/__snapshots__/converters.test.ts.snap
- src/steps/cloud-asset/converters.ts
- src/steps/cloud-asset/index.test.ts
- src/steps/cloud-asset/index.ts
Not every Google Cloud organization structure will have access to the projectId in the jobState, so instead of erroring, we just store the projectName instead.
> Prevent unable to find project id error

- jupiterone/questions/questions.yaml
Very simple PR that just adds one managed question for a property that's been covered already - in light of recent customer requests regarding GCP's Kubernetes.
> Add managed question for useRoutes

- CHANGELOG.md
- src/steps/cloud-asset/constants.ts
- src/steps/cloud-asset/index.ts
- src/utils/iamBindings/__snapshots__/getTypeAndKeyFromResourceIdentifier.test.ts.snap
- src/utils/iamBindings/getTypeAndKeyFromResourceIdentifier.test.ts
- src/utils/iamBindings/getTypeAndKeyFromResourceIdentifier.ts
- src/utils/iamBindings/resourceKindToTypeMap.ts
- src/utils/iamBindings/typeToKeyGeneratorMap.test.ts
- src/utils/iamBindings/typeToKeyGeneratorMap.ts
It might make sense to have these `_types` be all the same in order to more accurately map to what Google Cloud thinks about these SQL instance entities. However, that requires changing managed question and notifying customers. 
The code to do that is https://github.com/JupiterOne/graph-google-cloud/pull/376
...which is quite expensive and a big hassle as we have already created managed questions for this data model. Because of this it is likely better to just stick with the existing types.
> INT-1303 - Only map on _key when making any resource relationships with SQL instances

- CHANGELOG.md
- src/getStepStartStates.ts
- src/steps/enablement.test.ts
- src/steps/enablement.ts
Fixing an issue from a deploy earlier today where I thought `createStepStartState` would require both services to be enabled in order to enable the step. Instead it just checks if one of the services is required. I added a new method `createStepStartStateWhereAllServicesMustBeEnabled` to make this more clear.
> Ensure that both IAM and Cloud Asset APIs are enabled to run Cloud Asset steps

- CHANGELOG.md
- docs/jupiterone.md
- src/steps/cloud-asset/constants.ts
- src/steps/cloud-asset/index.ts
- src/utils/iamBindings/typeToKeyGeneratorMap.test.ts
`google_iam_binding_allows_resource` mapped relationships were getting created with a class of `HAS` instead of `ALLOWS`.
There was also a documentation issue where the `BINDING_ALLOWS_ANY_RESOURCE_RELATIONSHIP` stepMetadata was incorrect, which _might_ (unsure) have been causing partial_types to not have been specified properly during execution.
> Fix binding allows any resource mapped relationships to use ALLOWS instead of HAS

- CHANGELOG.md
- src/index.ts
- src/steps/cloud-asset/index.test.ts
- src/steps/cloud-asset/index.ts
- src/steps/compute/__snapshots__/index.test.ts.snap
- src/utils/maybeDefaultProjectIdOnEntity.test.ts
- src/utils/maybeDefaultProjectIdOnEntity.ts
This has caused confusion when using projectId to search off of. A more permeant solution for this might be to go into every converter and manually add the projectId. I opted not to do that in this PR in order to maintain a light-touch, but it would be more clear if we switched to that method.
> INTS-122 - Do not store projectId on entities that are not related to the project

- CHANGELOG.md
- src/steps/cloud-asset/__snapshots__/converters.test.ts.snap
- src/steps/cloud-asset/converters.ts
- src/steps/compute/__snapshots__/index.test.ts.snap
This was originally taken out because it was assumed that this was causing a RequestTooLarge exception. This was not the issue and can thus be safely be re-added. Plus, the rawData for bindings is actually really small. Example:
```
"_rawData": [
{
"name": "default",
"rawData": {
"role": "roles/cloudkms.serviceAgent",
"members": [
"serviceAccount:service-167984947943@gcp-sa-cloudkms.iam.gserviceaccount.com"
]
}
}
]
```
> Store rawData on google_iam_bindings again

- CHANGELOG.md
- src/steps/cloud-asset/constants.ts
- src/steps/cloud-asset/index.ts
This was originally done because we believed that `google_iam_binding`s were too large to be uploaded via lambda. This turned out not to be the case, so it is safe to index again. 
The reason why we need to index this data again is because I believe it is causing relationships to be skipped (and thus deleted) in very small integrations. I haven't been able to reproduce this yet, but there does seem like there could be a race-condition problem with the non-indexed uploads.
> Index binding relationship metadata again

- CHANGELOG.md
- src/steps/cloud-asset/index.ts
When making `google_iam_binding_allows_resource` relationships, we no longer check the if a service is enabled when determining if the relationship should be mapped or direct. This is because for non-organization integration instances, the Resource Manager API does not need to be enabled to ingest a `google_cloud_project`, so we would incorrectly make a mapped relationship when it should have been direct. This was added as an optimization that does not speed up the integration much anyway, so it makes sense to just remove it.
> Always check the jobState when making google_iam_binding relationships

- CHANGELOG.md
- src/utils/iamBindings/__snapshots__/getTypeAndKeyFromResourceIdentifier.test.ts.snap
- src/utils/iamBindings/getTypeAndKeyFromResourceIdentifier.test.ts
- src/utils/iamBindings/typeToKeyGeneratorMap.ts
`google_iam_binding` => `google_bigquery_table` relationships were not getting created because the `_key` that is used when creating the relationship was getting generated like:
`j1-gc-integration-dev-v3:test_big_query_dataset:Test Table` instead of
`j1-gc-integration-dev-v3:test_big_query_dataset.Test Table`
If you squint, you can notice the `:` instead of `.` before "Test Table".
> Generate Google Big Query Table keys correctly when making `google_iam_binding_allows_resource` relationships

- src/steps/big-query/__recordings__/fetchBigQueryModels_1144670279/recording.har
- src/steps/big-query/__snapshots__/converters.test.ts.snap
- src/steps/big-query/__snapshots__/index.test.ts.snap
- src/steps/big-query/converters.test.ts
- src/steps/big-query/converters.ts
- src/steps/big-query/index.ts
- src/steps/compute/__snapshots__/index.test.ts.snap
This is a fix for an error reported by the Sentry (https://sentry.io/organizations/jupiterone/issues/2523219247/events/1be64ee5742e486eae980274f3fd71b6/?project=5871712&statsPeriod=14d).
This stemmed from the very basic BigQuery model key we were using before. The BigQuery datasets have a key of this format `j1-gc-integration-dev-v3:natality`, I've gone ahead and modified the model's keys to follow the same pattern, just with modelId appended at the end, e.g. `j1-gc-integration-dev-v3:natality:natality_model`.
Edit: need to modify converters.test.ts slightly for this change, doing that right now.
Edit 2: done.
P.S I'm not yet sure how to properly document these: Sentry/AWS Cloudwatch -> PR -> resolution. I'm guessing I should also create a Jira ticket for this, and somehow match the …
> Add better BigQuery model key

- .github/workflows/build.yml
- .github/workflows/questions.yml
- package.json
The existing workflow prevents forked PRs from ever passing, because they are disallowed access to the proper environment variables. This was first experienced in https://github.com/JupiterOne/graph-azure/pull/450 
Specifically, this issue is holding up https://github.com/JupiterOne/graph-google-cloud/pull/415
> Allow forks to execute questions file

- docs/development.md
- src/getStepStartStates.ts
- src/google-cloud/client.ts
- src/index.ts
- src/steps/resource-manager/index.ts
- src/types.ts
Adding in optional FOLDER_ID to filter down to a specific folder within an organization for ingestion.  This is currently only restricting what folders and projects are ingested and is not doing anything to further restrict other entities.  We may want to rework or add additional filtering based on user or developer feedback.
> Adding in optional FOLDER_ID to filter by folder

- src/steps/cloud-run/__snapshots__/converters.test.ts.snap
- src/steps/cloud-run/__snapshots__/index.test.ts.snap
- src/steps/cloud-run/converters.test.ts
- src/steps/cloud-run/converters.ts
- src/steps/cloud-run/index.ts
- src/utils/iamBindings/__snapshots__/getTypeAndKeyFromResourceIdentifier.test.ts.snap
- src/utils/iamBindings/typeToKeyGeneratorMap.ts
- src/utils/jobState.ts
This PR fixes the bug associated with Cloud Asset's `createApiServiceToAnyResourceRelationships` step trying to process `iamBinding` that is related to Cloud Run service.
A different key format was used for Cloud Run Service than what the above-mentioned step was searching for, resulting in it failing to find it and ending up creating multiple mapped relationships where it ultimately failed with "Duplicate _key detected" error.
I had to introduce [cacheCloudRunServiceKeyAndUid](https://github.com/JupiterOne/graph-google-cloud/blob/fix/cloud-asset-cloud-run-key-bug/src/utils/jobState.ts#L29) since CloudRunRoutes and CloudRunConfigurations needed to find the CloudRunService, however, they have the `uid` and not all of the necessary parameters for creating the new key. This allows them to …
> INT-2448 - Change cloud run service key and its typeAndKeyFromResourceIdentifier

- CHANGELOG.md
- package.json
- src/google-cloud/client.ts
- Update retry `maxAttempts: 6` in `withErrorHandling`, increasing the total
retry time from 40s -> 90s
> Update retry maxAttempts to 6

- jupiterone/questions/questions.yaml
Allow a security reviewer with read-only access to audit a bigquery dataset with cloud API permissions.
> google-big-query-dataset-audit

- CHANGELOG.md
- jupiterone/questions/questions.yaml
- package.json
The requirement should have been using `google_user` instead of
`google_iam_service_account`.
> Fix CIS Google Cloud Foundations requirement 1.6

- CHANGELOG.md
- jupiterone/questions/questions.yaml
- package.json
The managed question `good` query is using the correct `_type`,
while the `bad` query is not. Both queries should be using
`google_user` instead of `google_iam_service_account`.
Additionally, both `good` and `bad` queries have been optimized
to use `WITH` query filters instead of `WHERE`, since `WITH`
performs post-traversal filtering.
> INT-3496 - Fix managed question to use correct `_type` query

- CHANGELOG.md
- src/steps/service-usage/client.ts
- src/steps/service-usage/index.ts
These changes makes GCP only iterate & ingest enabled services. This has the biggest impact on the number of requests that are needed for `fetch-api-services` step.
cc @ndowmon 
**Before**:
```
total requests made: 22
total resources returned: 2198
maximum resources (seen) per page: 100
```
**After**:
```
total requests made: 1
total resources returned: 52
maximum resources (seen) per page: 52
```
> INT-3572 - Iterate only enabled services

- jupiterone/questions/questions.yaml
We no longer ingest `google_cloud_api_service with enabled = false`
> Remove google_cloud_api_service with enabled = false question

- CHANGELOG.md
- docs/jupiterone.md
- src/steps/storage/index.ts
Our messaging asked users to add the `orgpolicy.policies.get` permission, but it actually should have been `orgpolicy.policy.get`.
> Fix orgpolicy.policy.get permission refs

- docs/jupiterone.md
For BigQuery:
`bigquery.datasets.get`
This allows integration to see datasets (datasets house models/tables, so this is the starting point). If this permission isn’t set, the integration won’t show an error but the resulting datasets response will just be an empty list (it’s due to how GCP decided to make that particular endpoint work).
However with just that one permission added, the integration won’t be able to process the tables and models fully (it’ll be able to see them but not get all the metadata), hence the following two permissions are recommended:
`bigquery.models.getMetadata`
`bigquery.tables.get`
So, in total the following permissions are required to make full use of our integration:
`bigquery.datasets.get`
`bigquery.models.getMetadata`
`bigquery.tables.get`
> INT-2289 - Update docs regarding BigQuery permissions

- CHANGELOG.md
- package.json
- src/getStepStartStates.ts
- src/index.test.ts
- src/steps/iam/constants.ts
- src/steps/iam/index.ts
- src/utils/iam.test.ts
- src/utils/iam.ts
If ingesting service APIs fails, we should still ingest custom IAM roles.
> INT-4146 - Split GCP service API to role relationship creation into separate step

- .github/workflows/build.yml
- .github/workflows/questions.yml
- package.json
- yarn.lock
Reverts JupiterOne/graph-google-cloud#500
The changes to polly.js have broken recordings in this project. Let's revert temporarily while we figure out a workaround, because this is blocking forward progress on new ingestion.
> Revert "Add graph:dependencies command, update deps"

- CHANGELOG.md
- package.json
- Support for new GCP compute regions
- Support optional `config.useEnablementsForStepStartStates` to call
listEnablements API before attempting to make API calls for all services
- Support the following new entities:
- `google_cloud_secret`
- `google_cloud_secret_version`
- `google_cloud_build`
- Do not throw if bigquery API returns
`The project ${config.projectId} has not enabled BigQuery.`
- Rely on the individual steps to call service APIs instead of pre-calculating
which service APIs are enabled in `getStepStartStates`. This should help
drastically reduce the number of API calls to `serviceusage.googleapis.com`.
- Change KMS key ring client request code to iterate hardcoded list of project
locations instead of hitting the KMS project location API. The KMS project
location API was …
> Release 2.16.0

- CHANGELOG.md
- docs/jupiterone.md
- src/steps/compute/__snapshots__/converters.test.ts.snap
- src/steps/compute/__snapshots__/index.test.ts.snap
- src/steps/compute/converters.ts
- src/steps/compute/index.test.ts
- New properties added to resources:
| Entity                          | Properties |
| ------------------------------- | ---------- |
| `google_compute_global_address` | `users`    |
| `google_compute_address`        | `users`    |
> INT-4507 - Add `users` property to compute address entities

- package.json
- yarn.lock
The reason behind this is to add support for new entities in cloudbuild that have been moved from alpha/beta to v1
> INT-5355 upgrade googleapis to support WorkerPools

- package.json
- yarn.lock
Support for GithubEnterpriseConfigs was added in v84;
https://github.com/googleapis/google-api-nodejs-client/blob/googleapis-v84.0.0/src/apis/cloudbuild/v1.ts#L870
> INT-5355 upgrade googleapis to support GithubEnterpriseConfigs

- src/google-cloud/client.test.ts
- src/google-cloud/client.ts
- src/steps/cloud-run/client.ts
- src/steps/compute/client.ts
- src/steps/sql-admin/client.ts
Pushed with `--no-verify` due to permission on my current user:
```
PollyError: [Polly] [persister:JupiterOneIntegationFSPersister] Cannot persist response for [GET] https://iam.googleapis.com/v1/roles?view=FULL&showDeleted=true because the status code was 401 and `recordFailedRequests` is `false`
PollyError: [Polly] [persister:JupiterOneIntegationFSPersister] Cannot persist response for [GET] https://iam.googleapis.com/v1/roles?view=FULL&showDeleted=true because the status code was 401 and `recordFailedRequests` is `false`
Provider API failed at https://iam.googleapis.com/v1/roles?view=FULL&showDeleted=true: 401 Unauthorized
```
> INT-5579 Decouple `iterateApi` into `forEachPage` and `withErrorHandling`

- .github/workflows/build.yml
We used to only fetch the latest 2 commits for versioning since HEAD-1 was the tagged commit. This leads to Auto not having visibility on all commits. We now fetch the entire commit history to allow Auto to properly create the changelog.
> Update fetch-depth for Auto

- docs/jupiterone.md
- docs/spec/src/steps/services/functions/index.ts
- src/getStepStartStates.ts
- src/index.test.ts
- src/steps/functions/__recordings__/build-cloud-function-source-repo-relationships_912814797/recording.har
- src/steps/functions/__recordings__/build-cloud-function-storage-bucket-relationships_1146849873/recording.har
- src/steps/functions/constants.ts
- src/steps/functions/index.test.ts
- src/steps/functions/index.ts
Adds Google Cloud Functions Source Repository Relation.
> feat(INT-5917): add cloud function storage bucket relationship

- src/steps/storage/index.ts
Add a warn statement if we receive an error when attempting to fetch organization public access prevention policies.
> INT-5867 Log fetch org public access prevention policy errors

- src/steps/cloud-build/client.ts
- src/steps/cloud-build/steps/fetch-cloud-build-bb-repos.ts
Context: 
Google Cloud does not handle correctly errors when BitBucket credentials are expired. Added a log in order to make it more easy to debug in the future.
> fix(INT-6744): add debug log if timeout error

- package.json
- src/google-cloud/client.ts
- src/steps/big-query/client.ts
- src/steps/storage/client.test.ts
- src/steps/storage/client.ts
Pull in `executeConcurrently` client method from `graph-aws` in order to add concurrency to paginated API calls.
> Speed up buckets and tables

- src/steps/resource-manager/index.test.ts
- src/steps/resource-manager/index.ts
Google's `auditLogConfig.exemptedMembers` response is the following:
```
auditLogConfig [
{
logType: 'ADMIN_READ',
exemptedMembers: [ 'user:gaston.yelmini@contractor.jupiterone.com' ]
},
{
logType: 'DATA_READ',
exemptedMembers: [ 'user:gaston.yelmini@contractor.jupiterone.com' ]
}
]
```
This is generating a duplicated key error when a member is included in one or more actions. 
Merge relationships additionalProperties `logType ` and avoid adding it twice to the jobState.
> INT-7619: fix duplicated Audit Config IAM Policy relationship key

- src/utils/isSingleProjectInstance.ts
Fix org steps running with undefined project id. This issue was caused by an `undefined` project id config that is possible scenario.
> INT-7798: fix org steps running with undefined project id

- src/steps/big-query/index.test.ts
- src/steps/big-query/index.ts
Added error handling in case dataset/tables returns 404
> FIX(int-7914) Added error handling in case dataset/tables returns 404
